language: ruby
rvm:
  - 2.4.1
  -
before_script:
  - chmod +x ./ci/build.sh

script: ./ci/build.sh

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
