# Jekyll configuration that is language-agnostic.
#
# To run Jekyll, two configuration files need to be specified, in this order:
#
#     jekyll --config _config.yml,_config_en.yml
#     jekyll --config _config.yml,_config_de.yml

title: Peter Grassberger
email: petertheone@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://petergrassberger.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: petertheone
github_username:  petertheone

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap

permalink: /blog/:title/

collections:
 projects:
  output: true
  permalink: /projects/:title/

# todo: maybe move to /feed/ because now it isn't an rss feed
feed:
  path: /rss/index.xml


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Settings overridden by language-specific configs
destination: "/ See _config.yml on how to build this thing"
exclude: ["vendor", "*.??.html", "Gemfile", "Gemfile.lock"]
